version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: sonata-project/admin-bundle
    versions:
    - 3.88.0
    - 3.89.1
    - 3.91.0
    - 3.91.1
    - 3.92.0
    - 3.93.0
    - 3.94.0
    - 3.95.0
    - 3.96.0
    - 3.97.0
  - dependency-name: symfony/http-client-contracts
    versions:
    - 2.4.0
  - dependency-name: symfony/deprecation-contracts
    versions:
    - 2.4.0
  - dependency-name: doctrine/dbal
    versions:
    - 2.13.1
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - 3.0.2
    - 3.1.0
  - dependency-name: symfony/security-http
    versions:
    - 4.4.19
    - 4.4.20
    - 4.4.21
  - dependency-name: symfony/error-handler
    versions:
    - 4.4.21
  - dependency-name: symfony/mime
    versions:
    - 5.2.6
  - dependency-name: symfony/inflector
    versions:
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/filesystem
    versions:
    - 5.2.6
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.21
  - dependency-name: jms/serializer
    versions:
    - 3.12.1
    - 3.12.2
  - dependency-name: phpstan/phpdoc-parser
    versions:
    - 0.4.13
    - 0.4.14
  - dependency-name: jms/metadata
    versions:
    - 2.5.0
  - dependency-name: symfony/var-dumper
    versions:
    - 5.2.5
  - dependency-name: sonata-project/block-bundle
    versions:
    - 3.22.1
  - dependency-name: symfony/routing
    versions:
    - 4.4.19
  - dependency-name: symfony/twig-bridge
    versions:
    - 4.4.19
  - dependency-name: symfony/monolog-bridge
    versions:
    - 5.2.3
  - dependency-name: symfony/asset
    versions:
    - 4.4.19
  - dependency-name: symfony/debug
    versions:
    - 4.4.19
  - dependency-name: doctrine/common
    versions:
    - 3.1.1
  - dependency-name: symfony/console
    versions:
    - 4.4.19
  - dependency-name: symfony/polyfill-intl-icu
    versions:
    - 1.22.0
  - dependency-name: doctrine/orm
    versions:
    - 2.8.1
