security:
    # encoders:
    #     FOS\UserBundle\Model\UserInterface: auto
    access_control:
        # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
    # role_hierarchy:
    #     ROLE_ADMIN:
    #         - ROLE_USER
    #         - ROLE_SONATA_ADMIN
    #         - ROLE_SONATA_USER_ADMIN_USER_VIEW
    #     ROLE_SUPER_ADMIN:
    #         - ROLE_ADMIN
    #         - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    # providers:
    #     backoffice:
    #         id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # backoffice:
        #     anonymous: lazy
        #     pattern: /(.*)
        #     provider: backoffice
        #     context: user
        #     switch_user: true
        #     form_login:
        #         login_path: /login
        #         check_path: /login_check
        #         default_target_path: sonata_admin_dashboard
        #     logout:
        #         path: /logout
        #         target: /login
        #     remember_me:
        #         secret: '%env(APP_SECRET)%'
        #         lifetime: 2629746
        #         path: /
