---
- name: Install apache
  become: true
  apt:
    name: apache2
    state: latest

- name: Enable apache modules
  become: true
  apache2_module:
    name: '{{ item }}'
    state: present
  notify: Restart apache
  with_items: '{{ apache.modules }}'

- name: Copy common config
  become: true
  template:
    src: common.conf
    dest: /etc/apache2/common.conf
  notify: Restart apache

- name: Change default apache site
  become: true
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart apache

- include: ssl.yml
