---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:ondrej/apache2

- name: Install apache
  become: true
  apt:
    name: apache2
    state: latest

- name: Enable apache modules
  become: true
  apache2_module:
    name: '{{ item }}'
  with_items: '{{ apache.modules }}'
  notify: Restart apache

- name: Copy common config
  become: true
  template:
    src: common.conf
    dest: /etc/apache2/common.conf
  notify: Restart apache

- name: Change default apache site
  become: true
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart apache

- name: Copy .htaccess
  template:
    src: .htaccess
    dest: /vagrant/web

- name: Add phpmyadmin to apache
  become: true
  lineinfile:
    dest: /etc/apache2/apache2.conf
    line: 'Include /etc/phpmyadmin/apache.conf'
  notify: Restart apache
