---
- name: Generate rsa key
  command: openssl genrsa -out /etc/ssl/private/ssl.key 2048
  args:
    creates: /etc/ssl/private/ssl.key

- name: Generate self-signed ssl certificate
  command: >
    openssl req
      -new -x509 -days 3650
      -key /etc/ssl/private/ssl.key
      -out /etc/ssl/certs/ssl.cert
      -subj {% for alias in apache.serveralias %}/CN={{ alias }}{% endfor %}/CN={{ apache.servername }}
  args:
    creates: /etc/ssl/certs/ssl.cert
