syncs:
    sonata-sync:
        src: '..'
        dest: '/var/www/html'
        sync_user: 33
        sync_group: 33
        sync_host_port: 10871

options:
    compose-file-path: 'docker-compose.yml'
    compose-dev-file-path: 'docker-compose-osx.yml'
