version: '2.1'

services:
    sonata:
        build: ./apache-php
        hostname: sonata
        container_name: sonata
        ports:
            - 8080:80
            - 9001:9000

    database:
        image: mysql:latest
        hostname: database
        environment:
            MYSQL_DATABASE: sonata
            MYSQL_USER: sonata
            MYSQL_PASSWORD: sonata
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_PORT: 3306
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8081:80
