---
- name: Install mysql packages
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Drop database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    state: absent
  tags:
    - database

- name: Create database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    encoding: utf8
  tags:
    - database

- name: Import database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    state: import
    target: /vagrant/{{ mysql.dump }}
  when: mysql.dump
  tags:
    - database

- name: Create user
  become: true
  mysql_user:
    name: '{{ mysql.user }}'
    password: '{{ mysql.password }}'
    priv: '{{ mysql.database }}.*:ALL'
