---
- name: Install mysql packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Drop database
  mysql_db:
    name: '{{ mysql.database }}'
    state: absent

- name: Create database
  mysql_db:
    name: '{{ mysql.database }}'
    encoding: utf8
    state: present

- name: Import database
  mysql_db:
    name: '{{ mysql.database }}'
    state: import
    target: /vagrant/{{ mysql.dump }}
  when: mysql.dump

- name: Create user
  mysql_user:
    name: '{{ mysql.user }}'
    password: '{{ mysql.password }}'
    priv: '{{ mysql.database }}.*:ALL'
    state: present
