---
- name: Create symfony files
  become: false
  template:
    src: '{{ item.file }}'
    dest: '/tmp/{{ item.file }}'
  with_items: '{{ symfony.files }}'
  when: symfony.files is defined

- name: Move symfony files
  become: false
  command: 'cp /tmp/{{ item.file }} {{ item.dest }}/{{ item.file }}'
  with_items: '{{ symfony.files }}'
  when: symfony.files is defined

- include: permissions.yml
  when: symfony.permission_dirs is defined
