---
- name: Set correct permissions
  become: true
  acl:
    name: '{{ ansible_env.HOME }}/{{ item }}'
    entity: www-data
    etype: user
    permissions: rwX
    default: no
    recursive: yes
    state: present
  with_items: '{{ symfony.permission_dirs }}'

- name: Set correct permissions
  become: true
  acl:
    name: '{{ ansible_env.HOME }}/{{ item }}'
    entity: www-data
    etype: user
    permissions: rwX
    default: yes
    recursive: yes
    state: present
  with_items: '{{ symfony.permission_dirs }}'

- name: Set correct permissions
  become: true
  acl:
    name: '{{ ansible_env.HOME }}/{{ item }}'
    entity: '{{ ansible_env.USER }}'
    etype: user
    permissions: rwX
    default: no
    recursive: yes
    state: present
  with_items: '{{ symfony.permission_dirs }}'

- name: Set correct permissions
  become: true
  acl:
    name: '{{ ansible_env.HOME }}/{{ item }}'
    entity: '{{ ansible_env.USER }}'
    etype: user
    permissions: rwX
    default: yes
    recursive: yes
    state: present
  with_items: '{{ symfony.permission_dirs }}'
