services:
    sonata.base.admin.book:
        class: Sonata\BaseBundle\Admin\BookAdmin
        arguments: [~, Sonata\BaseBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Sonata, label: Books }

    sonata.base.admin.category:
        class: Sonata\BaseBundle\Admin\CategoryAdmin
        arguments: [~, Sonata\BaseBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Sonata, label: Categories }

    sonata.base.admin.review:
        class: Sonata\BaseBundle\Admin\ReviewAdmin
        arguments: [~, Sonata\BaseBundle\Entity\Review, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Reviews, show_in_dashboard: false }
