parameters:
    locale: en
    container.dumper.inline_class_loader: true

services:
    App\Admin\BookAdmin:
        public: true
        arguments: [~, App\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Books }

    App\Admin\CategoryAdmin:
        public: true
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categories }

    App\Admin\ReviewAdmin:
        public: true
        arguments: [~, App\Entity\Review, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Reviews, show_in_dashboard: false }
