services:
    app.base.admin.book:
        class: App\BaseBundle\Admin\BookAdmin
        public: true
        arguments: [~, App\BaseBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Books }

    app.base.admin.category:
        class: App\BaseBundle\Admin\CategoryAdmin
        public: true
        arguments: [~, App\BaseBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categories }

    app.base.admin.review:
        class: App\BaseBundle\Admin\ReviewAdmin
        public: true
        arguments: [~, App\BaseBundle\Entity\Review, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Reviews, show_in_dashboard: false }
