name: Approve Pull Request

on:
  pull_request:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'jordisala'
    # if: ${{ github.event.pull_request.title == 'Test' }}
    steps:
      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v3
